// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knn_reference_cpp
List knn_reference_cpp(NumericMatrix pca_corrected, IntegerVector masked_bins_per_chr, IntegerVector masked_bins_per_chr_cum, int refsize, std::string gender, int cpus);
RcppExport SEXP _RWisecondorX_knn_reference_cpp(SEXP pca_correctedSEXP, SEXP masked_bins_per_chrSEXP, SEXP masked_bins_per_chr_cumSEXP, SEXP refsizeSEXP, SEXP genderSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr(masked_bins_per_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr_cum(masked_bins_per_chr_cumSEXP);
    Rcpp::traits::input_parameter< int >::type refsize(refsizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type gender(genderSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_reference_cpp(pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus));
    return rcpp_result_gen;
END_RCPP
}
// null_ratios_cpp
NumericMatrix null_ratios_cpp(NumericMatrix pca_corrected, IntegerMatrix indexes, IntegerVector null_sample_idx, int cpus);
RcppExport SEXP _RWisecondorX_null_ratios_cpp(SEXP pca_correctedSEXP, SEXP indexesSEXP, SEXP null_sample_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type null_sample_idx(null_sample_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(null_ratios_cpp(pca_corrected, indexes, null_sample_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RWisecondorX_knn_reference_cpp", (DL_FUNC) &_RWisecondorX_knn_reference_cpp, 6},
    {"_RWisecondorX_null_ratios_cpp", (DL_FUNC) &_RWisecondorX_null_ratios_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RWisecondorX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
