// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knn_reference_cpp
List knn_reference_cpp(NumericMatrix pca_corrected, IntegerVector masked_bins_per_chr, IntegerVector masked_bins_per_chr_cum, int refsize, std::string gender, int cpus);
RcppExport SEXP _RWisecondorX_knn_reference_cpp(SEXP pca_correctedSEXP, SEXP masked_bins_per_chrSEXP, SEXP masked_bins_per_chr_cumSEXP, SEXP refsizeSEXP, SEXP genderSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr(masked_bins_per_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr_cum(masked_bins_per_chr_cumSEXP);
    Rcpp::traits::input_parameter< int >::type refsize(refsizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type gender(genderSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_reference_cpp(pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus));
    return rcpp_result_gen;
END_RCPP
}
// null_ratios_cpp
NumericMatrix null_ratios_cpp(NumericMatrix pca_corrected, IntegerMatrix indexes, IntegerVector null_sample_idx, int cpus);
RcppExport SEXP _RWisecondorX_null_ratios_cpp(SEXP pca_correctedSEXP, SEXP indexesSEXP, SEXP null_sample_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type null_sample_idx(null_sample_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(null_ratios_cpp(pca_corrected, indexes, null_sample_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ssd_scores_cpp
NumericVector nipter_ssd_scores_cpp(NumericMatrix fracs, NumericVector query, IntegerVector compare_idx, int cpus);
RcppExport SEXP _RWisecondorX_nipter_ssd_scores_cpp(SEXP fracsSEXP, SEXP querySEXP, SEXP compare_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type compare_idx(compare_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ssd_scores_cpp(fracs, query, compare_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ssd_matrix_cpp
NumericMatrix nipter_ssd_matrix_cpp(NumericMatrix fracs, IntegerVector compare_idx, int cpus);
RcppExport SEXP _RWisecondorX_nipter_ssd_matrix_cpp(SEXP fracsSEXP, SEXP compare_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type compare_idx(compare_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ssd_matrix_cpp(fracs, compare_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ncv_search_cpp
List nipter_ncv_search_cpp(NumericMatrix ctrl_reads, IntegerVector candidates, int focus_row, int max_elements);
RcppExport SEXP _RWisecondorX_nipter_ncv_search_cpp(SEXP ctrl_readsSEXP, SEXP candidatesSEXP, SEXP focus_rowSEXP, SEXP max_elementsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ctrl_reads(ctrl_readsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< int >::type focus_row(focus_rowSEXP);
    Rcpp::traits::input_parameter< int >::type max_elements(max_elementsSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ncv_search_cpp(ctrl_reads, candidates, focus_row, max_elements));
    return rcpp_result_gen;
END_RCPP
}
// nipter_stepwise_cpp
IntegerVector nipter_stepwise_cpp(NumericMatrix fracs, int focus_row, IntegerVector cand_rows, int n_step);
RcppExport SEXP _RWisecondorX_nipter_stepwise_cpp(SEXP fracsSEXP, SEXP focus_rowSEXP, SEXP cand_rowsSEXP, SEXP n_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< int >::type focus_row(focus_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cand_rows(cand_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_step(n_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_stepwise_cpp(fracs, focus_row, cand_rows, n_step));
    return rcpp_result_gen;
END_RCPP
}
// samtools_stats_summary_cpp
List samtools_stats_summary_cpp(std::string path, std::string reference, int min_mapq, int require_flags, int exclude_flags, int decompression_threads, bool report_filtered_stream_bookkeeping);
RcppExport SEXP _RWisecondorX_samtools_stats_summary_cpp(SEXP pathSEXP, SEXP referenceSEXP, SEXP min_mapqSEXP, SEXP require_flagsSEXP, SEXP exclude_flagsSEXP, SEXP decompression_threadsSEXP, SEXP report_filtered_stream_bookkeepingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type require_flags(require_flagsSEXP);
    Rcpp::traits::input_parameter< int >::type exclude_flags(exclude_flagsSEXP);
    Rcpp::traits::input_parameter< int >::type decompression_threads(decompression_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type report_filtered_stream_bookkeeping(report_filtered_stream_bookkeepingSEXP);
    rcpp_result_gen = Rcpp::wrap(samtools_stats_summary_cpp(path, reference, min_mapq, require_flags, exclude_flags, decompression_threads, report_filtered_stream_bookkeeping));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RWisecondorX_knn_reference_cpp", (DL_FUNC) &_RWisecondorX_knn_reference_cpp, 6},
    {"_RWisecondorX_null_ratios_cpp", (DL_FUNC) &_RWisecondorX_null_ratios_cpp, 4},
    {"_RWisecondorX_nipter_ssd_scores_cpp", (DL_FUNC) &_RWisecondorX_nipter_ssd_scores_cpp, 4},
    {"_RWisecondorX_nipter_ssd_matrix_cpp", (DL_FUNC) &_RWisecondorX_nipter_ssd_matrix_cpp, 3},
    {"_RWisecondorX_nipter_ncv_search_cpp", (DL_FUNC) &_RWisecondorX_nipter_ncv_search_cpp, 4},
    {"_RWisecondorX_nipter_stepwise_cpp", (DL_FUNC) &_RWisecondorX_nipter_stepwise_cpp, 4},
    {"_RWisecondorX_samtools_stats_summary_cpp", (DL_FUNC) &_RWisecondorX_samtools_stats_summary_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RWisecondorX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
