// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate_trisomy_bam_cpp
List simulate_trisomy_bam_cpp(const std::string& input_path, const std::string& output_path, const std::string& trisomy_chr, const double other_keep_prob, const int seed, const int threads, const std::string& reference);
RcppExport SEXP _RWisecondorX_simulate_trisomy_bam_cpp(SEXP input_pathSEXP, SEXP output_pathSEXP, SEXP trisomy_chrSEXP, SEXP other_keep_probSEXP, SEXP seedSEXP, SEXP threadsSEXP, SEXP referenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type input_path(input_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_path(output_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type trisomy_chr(trisomy_chrSEXP);
    Rcpp::traits::input_parameter< const double >::type other_keep_prob(other_keep_probSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type reference(referenceSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_trisomy_bam_cpp(input_path, output_path, trisomy_chr, other_keep_prob, seed, threads, reference));
    return rcpp_result_gen;
END_RCPP
}
// write_synthetic_bam_cpp
double write_synthetic_bam_cpp(const std::string& path, const CharacterVector& chr_names, const IntegerVector& chr_lengths, const List& positions_by_chr, const int read_len, const int mapq, const int threads);
RcppExport SEXP _RWisecondorX_write_synthetic_bam_cpp(SEXP pathSEXP, SEXP chr_namesSEXP, SEXP chr_lengthsSEXP, SEXP positions_by_chrSEXP, SEXP read_lenSEXP, SEXP mapqSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type chr_names(chr_namesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type chr_lengths(chr_lengthsSEXP);
    Rcpp::traits::input_parameter< const List& >::type positions_by_chr(positions_by_chrSEXP);
    Rcpp::traits::input_parameter< const int >::type read_len(read_lenSEXP);
    Rcpp::traits::input_parameter< const int >::type mapq(mapqSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(write_synthetic_bam_cpp(path, chr_names, chr_lengths, positions_by_chr, read_len, mapq, threads));
    return rcpp_result_gen;
END_RCPP
}
// knn_reference_cpp
List knn_reference_cpp(NumericMatrix pca_corrected, IntegerVector masked_bins_per_chr, IntegerVector masked_bins_per_chr_cum, int refsize, std::string gender, int cpus);
RcppExport SEXP _RWisecondorX_knn_reference_cpp(SEXP pca_correctedSEXP, SEXP masked_bins_per_chrSEXP, SEXP masked_bins_per_chr_cumSEXP, SEXP refsizeSEXP, SEXP genderSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr(masked_bins_per_chrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type masked_bins_per_chr_cum(masked_bins_per_chr_cumSEXP);
    Rcpp::traits::input_parameter< int >::type refsize(refsizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type gender(genderSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_reference_cpp(pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus));
    return rcpp_result_gen;
END_RCPP
}
// null_ratios_cpp
NumericMatrix null_ratios_cpp(NumericMatrix pca_corrected, IntegerMatrix indexes, IntegerVector null_sample_idx, int cpus);
RcppExport SEXP _RWisecondorX_null_ratios_cpp(SEXP pca_correctedSEXP, SEXP indexesSEXP, SEXP null_sample_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pca_corrected(pca_correctedSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type indexes(indexesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type null_sample_idx(null_sample_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(null_ratios_cpp(pca_corrected, indexes, null_sample_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ssd_scores_cpp
NumericVector nipter_ssd_scores_cpp(NumericMatrix fracs, NumericVector query, IntegerVector compare_idx, int cpus);
RcppExport SEXP _RWisecondorX_nipter_ssd_scores_cpp(SEXP fracsSEXP, SEXP querySEXP, SEXP compare_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type compare_idx(compare_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ssd_scores_cpp(fracs, query, compare_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ssd_matrix_cpp
NumericMatrix nipter_ssd_matrix_cpp(NumericMatrix fracs, IntegerVector compare_idx, int cpus);
RcppExport SEXP _RWisecondorX_nipter_ssd_matrix_cpp(SEXP fracsSEXP, SEXP compare_idxSEXP, SEXP cpusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type compare_idx(compare_idxSEXP);
    Rcpp::traits::input_parameter< int >::type cpus(cpusSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ssd_matrix_cpp(fracs, compare_idx, cpus));
    return rcpp_result_gen;
END_RCPP
}
// nipter_ncv_search_cpp
List nipter_ncv_search_cpp(NumericMatrix ctrl_reads, IntegerVector candidates, int focus_row, int max_elements);
RcppExport SEXP _RWisecondorX_nipter_ncv_search_cpp(SEXP ctrl_readsSEXP, SEXP candidatesSEXP, SEXP focus_rowSEXP, SEXP max_elementsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ctrl_reads(ctrl_readsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< int >::type focus_row(focus_rowSEXP);
    Rcpp::traits::input_parameter< int >::type max_elements(max_elementsSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_ncv_search_cpp(ctrl_reads, candidates, focus_row, max_elements));
    return rcpp_result_gen;
END_RCPP
}
// nipter_stepwise_cpp
IntegerVector nipter_stepwise_cpp(NumericMatrix fracs, int focus_row, IntegerVector cand_rows, int n_step);
RcppExport SEXP _RWisecondorX_nipter_stepwise_cpp(SEXP fracsSEXP, SEXP focus_rowSEXP, SEXP cand_rowsSEXP, SEXP n_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fracs(fracsSEXP);
    Rcpp::traits::input_parameter< int >::type focus_row(focus_rowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cand_rows(cand_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_step(n_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(nipter_stepwise_cpp(fracs, focus_row, cand_rows, n_step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RWisecondorX_simulate_trisomy_bam_cpp", (DL_FUNC) &_RWisecondorX_simulate_trisomy_bam_cpp, 7},
    {"_RWisecondorX_write_synthetic_bam_cpp", (DL_FUNC) &_RWisecondorX_write_synthetic_bam_cpp, 7},
    {"_RWisecondorX_knn_reference_cpp", (DL_FUNC) &_RWisecondorX_knn_reference_cpp, 6},
    {"_RWisecondorX_null_ratios_cpp", (DL_FUNC) &_RWisecondorX_null_ratios_cpp, 4},
    {"_RWisecondorX_nipter_ssd_scores_cpp", (DL_FUNC) &_RWisecondorX_nipter_ssd_scores_cpp, 4},
    {"_RWisecondorX_nipter_ssd_matrix_cpp", (DL_FUNC) &_RWisecondorX_nipter_ssd_matrix_cpp, 3},
    {"_RWisecondorX_nipter_ncv_search_cpp", (DL_FUNC) &_RWisecondorX_nipter_ncv_search_cpp, 4},
    {"_RWisecondorX_nipter_stepwise_cpp", (DL_FUNC) &_RWisecondorX_nipter_stepwise_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RWisecondorX(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
