# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_reference_cpp <- function(pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus) {
    .Call(`_RWisecondorX_knn_reference_cpp`, pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus)
}

null_ratios_cpp <- function(pca_corrected, indexes, null_sample_idx, cpus) {
    .Call(`_RWisecondorX_null_ratios_cpp`, pca_corrected, indexes, null_sample_idx, cpus)
}

nipter_ssd_scores_cpp <- function(fracs, query, compare_idx, cpus = 1L) {
    .Call(`_RWisecondorX_nipter_ssd_scores_cpp`, fracs, query, compare_idx, cpus)
}

nipter_ssd_matrix_cpp <- function(fracs, compare_idx, cpus = 1L) {
    .Call(`_RWisecondorX_nipter_ssd_matrix_cpp`, fracs, compare_idx, cpus)
}

