# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_trisomy_bam_cpp <- function(input_path, output_path, trisomy_chr, other_keep_prob, seed = 1L, threads = 1L, reference = "") {
    .Call(`_RWisecondorX_simulate_trisomy_bam_cpp`, input_path, output_path, trisomy_chr, other_keep_prob, seed, threads, reference)
}

write_synthetic_bam_cpp <- function(path, chr_names, chr_lengths, positions_by_chr, read_len = 36L, mapq = 60L, threads = 1L) {
    .Call(`_RWisecondorX_write_synthetic_bam_cpp`, path, chr_names, chr_lengths, positions_by_chr, read_len, mapq, threads)
}

knn_reference_cpp <- function(pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus) {
    .Call(`_RWisecondorX_knn_reference_cpp`, pca_corrected, masked_bins_per_chr, masked_bins_per_chr_cum, refsize, gender, cpus)
}

null_ratios_cpp <- function(pca_corrected, indexes, null_sample_idx, cpus) {
    .Call(`_RWisecondorX_null_ratios_cpp`, pca_corrected, indexes, null_sample_idx, cpus)
}

nipter_ssd_scores_cpp <- function(fracs, query, compare_idx, cpus = 1L) {
    .Call(`_RWisecondorX_nipter_ssd_scores_cpp`, fracs, query, compare_idx, cpus)
}

nipter_ssd_matrix_cpp <- function(fracs, compare_idx, cpus = 1L) {
    .Call(`_RWisecondorX_nipter_ssd_matrix_cpp`, fracs, compare_idx, cpus)
}

nipter_ncv_search_cpp <- function(ctrl_reads, candidates, focus_row, max_elements) {
    .Call(`_RWisecondorX_nipter_ncv_search_cpp`, ctrl_reads, candidates, focus_row, max_elements)
}

nipter_stepwise_cpp <- function(fracs, focus_row, cand_rows, n_step) {
    .Call(`_RWisecondorX_nipter_stepwise_cpp`, fracs, focus_row, cand_rows, n_step)
}

